// Generated by gencpp from file pses_basis/Command.msg
// DO NOT EDIT!


#ifndef PSES_BASIS_MESSAGE_COMMAND_H
#define PSES_BASIS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pses_basis/PsesHeader.h>

namespace pses_basis
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , steering_level(0)
    , motor_level(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_level(0)
    , motor_level(0)  {
  (void)_alloc;
    }



   typedef  ::pses_basis::PsesHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _steering_level_type;
  _steering_level_type steering_level;

   typedef int16_t _motor_level_type;
  _motor_level_type motor_level;




  typedef boost::shared_ptr< ::pses_basis::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pses_basis::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::pses_basis::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::pses_basis::Command > CommandPtr;
typedef boost::shared_ptr< ::pses_basis::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pses_basis::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pses_basis::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pses_basis

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pses_basis': ['/home/pses/catkin_ws/src/pses_basis/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pses_basis::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pses_basis::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pses_basis::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pses_basis::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pses_basis::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pses_basis::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pses_basis::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6ece05392ce6cfa1dc8b85398d5e9da";
  }

  static const char* value(const ::pses_basis::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6ece05392ce6cfaULL;
  static const uint64_t static_value2 = 0x1dc8b85398d5e9daULL;
};

template<class ContainerAllocator>
struct DataType< ::pses_basis::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pses_basis/Command";
  }

  static const char* value(const ::pses_basis::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pses_basis::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PsesHeader header\n\
int16 steering_level\n\
int16 motor_level\n\
\n\
================================================================================\n\
MSG: pses_basis/PsesHeader\n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch\n\
# * stamp.nsec: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
int16 car_id\n\
";
  }

  static const char* value(const ::pses_basis::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pses_basis::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_level);
      stream.next(m.motor_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pses_basis::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pses_basis::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::pses_basis::PsesHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering_level: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering_level);
    s << indent << "motor_level: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PSES_BASIS_MESSAGE_COMMAND_H
